// START

// SET x = 9
// SET y = 2
// SET z = 6

// SET a = x * y / z

// PRINT a

// END
public class Calculation {
    public static void main(String[] args) {
        // Declare and initialize integer variables
        int x = 9;
        int y = 2;
        int z = 6;
        
        // Declare integer variable 'a' and calculate its value
        int a = x * y / z;
        
        // Print the value of 'a'
        System.out.println(a);
    }
}